import React, { useState, useMemo } from 'react';
import {
  ChevronLeft,
  ChevronRight,
  Download,
  Printer,
  Plus,
  Trash2,
  Edit2,
  RotateCcw,
  Sparkles,
  Save,
  Calendar,
  AlertCircle
} from 'lucide-react';
import { SchoolConfig, PpctItem, TimetableSlot, LessonPlanRow } from '../types';
import { getWeekDateRange, getDateForDayOfWeek, getDayOfWeekName } from '../utils/dateUtils';
import { exportLessonPlanToDocx } from '../utils/docxExport';
import { LessonDetailModal } from './LessonDetailModal';

interface DocumentPreviewProps {
  config: SchoolConfig;
  ppctList: PpctItem[];
  timetable: TimetableSlot[];
  customizedWeeks: Record<number, LessonPlanRow[]>;
  onSaveWeekRows: (weekNumber: number, rows: LessonPlanRow[]) => void;
  onResetWeekRows: (weekNumber: number) => void;
}

export const DocumentPreview: React.FC<DocumentPreviewProps> = ({
  config,
  ppctList,
  timetable,
  customizedWeeks,
  onSaveWeekRows,
  onResetWeekRows
}) => {
  const [currentWeek, setCurrentWeek] = useState<number>(1);
  const [editingRow, setEditingRow] = useState<LessonPlanRow | null>(null);
  const [isExporting, setIsExporting] = useState<boolean>(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3000);
  };

  // Tính khoảng ngày của tuần hiện tại
  const weekDates = useMemo(() => {
    return getWeekDateRange(config.startDateWeek1 || '2024-09-09', currentWeek);
  }, [config.startDateWeek1, currentWeek]);

  // Tự động sinh danh sách tiết dạy từ Thời Khóa Biểu và PPCT cho tuần hiện tại
  const autoGeneratedRows: LessonPlanRow[] = useMemo(() => {
    // Sắp xếp TKB: Thứ (2->7), Buổi (morning trước afternoon), Tiết (1->5)
    const sortedSlots = [...timetable].sort((a, b) => {
      if (a.dayOfWeek !== b.dayOfWeek) return a.dayOfWeek - b.dayOfWeek;
      const sessionScore = (s: string) => (s === 'morning' || s === 'Sáng' ? 0 : 1);
      if (sessionScore(a.session) !== sessionScore(b.session)) {
        return sessionScore(a.session) - sessionScore(b.session);
      }
      return a.period - b.period;
    });

    // Theo dõi số tiết đã dạy của từng khối/môn trong tuần
    const subjectOccurrences: Record<string, number> = {};

    return sortedSlots.map((slot, index) => {
      const key = `${slot.grade}_${slot.subject}`;
      const count = (subjectOccurrences[key] || 0) + 1;
      subjectOccurrences[key] = count;

      // Tìm bài dạy trong PPCT theo khối, môn, tuần và số thứ tự tiết trong tuần
      const matchingPpct = ppctList.find(
        (p) =>
          Number(p.grade) === Number(slot.grade) &&
          p.subject.trim().toLowerCase() === slot.subject.trim().toLowerCase() &&
          Number(p.week) === currentWeek &&
          Number(p.periodIndex) === count
      ) || ppctList.find(
        (p) =>
          Number(p.grade) === Number(slot.grade) &&
          p.subject.trim().toLowerCase() === slot.subject.trim().toLowerCase() &&
          Number(p.week) === currentWeek
      );

      const dateStr = getDateForDayOfWeek(
        config.startDateWeek1 || '2024-09-09',
        currentWeek,
        slot.dayOfWeek
      );

      return {
        id: `row-${currentWeek}-${slot.id || index}`,
        dayOfWeek: slot.dayOfWeek,
        dateStr,
        session: slot.session === 'morning' || slot.session === 'Sáng' ? 'Sáng' : 'Chiều',
        period: slot.period,
        className: slot.className,
        subject: slot.subject,
        lessonName: matchingPpct?.lessonName || (slot.subject === 'Chào cờ' ? 'Chào cờ đầu tuần' : slot.subject === 'Sinh hoạt lớp' ? 'Sinh hoạt lớp cuối tuần' : `Bài học tuần ${currentWeek}`),
        integrationNote: matchingPpct?.integrationNote || '',
        isCustomized: false
      };
    });
  }, [timetable, ppctList, currentWeek, config.startDateWeek1]);

  // Hàng hiển thị: dùng hàng đã tùy chỉnh nếu có, nếu chưa thì dùng hàng tự động sinh
  const displayRows: LessonPlanRow[] = useMemo(() => {
    if (customizedWeeks[currentWeek] && customizedWeeks[currentWeek].length > 0) {
      return customizedWeeks[currentWeek];
    }
    return autoGeneratedRows;
  }, [customizedWeeks, currentWeek, autoGeneratedRows]);

  // Sắp xếp hàng chuẩn theo: Thứ (2 -> 7) -> Buổi (Sáng -> Chiều) -> Tiết (1 -> 5)
  const sortedDisplayRows = useMemo(() => {
    return [...displayRows].sort((a, b) => {
      if (a.dayOfWeek !== b.dayOfWeek) return a.dayOfWeek - b.dayOfWeek;
      const sessionOrder = (s: string) => (s === 'Sáng' || s === 'morning' ? 1 : 2);
      if (sessionOrder(a.session) !== sessionOrder(b.session)) {
        return sessionOrder(a.session) - sessionOrder(b.session);
      }
      return a.period - b.period;
    });
  }, [displayRows]);

  // Tính toán gộp ô (rowSpan) cho Thứ và Buổi giống hệt mẫu đính kèm
  const rowSpanData = useMemo(() => {
    const list = sortedDisplayRows;
    return list.map((row, idx) => {
      const isFirstOfDay = idx === 0 || row.dayOfWeek !== list[idx - 1].dayOfWeek;
      let daySpan = 0;
      if (isFirstOfDay) {
        let count = 0;
        for (let i = idx; i < list.length && list[i].dayOfWeek === row.dayOfWeek; i++) {
          count++;
        }
        daySpan = count;
      }

      const isFirstOfSession =
        isFirstOfDay || row.session !== list[idx - 1].session;
      let sessionSpan = 0;
      if (isFirstOfSession) {
        let count = 0;
        for (
          let i = idx;
          i < list.length &&
          list[i].dayOfWeek === row.dayOfWeek &&
          list[i].session === row.session;
          i++
        ) {
          count++;
        }
        sessionSpan = count;
      }

      return {
        row,
        daySpan,
        sessionSpan
      };
    });
  }, [sortedDisplayRows]);

  const handleUpdateRow = (updatedRow: LessonPlanRow) => {
    const newRows = displayRows.map((r) => (r.id === updatedRow.id ? updatedRow : r));
    onSaveWeekRows(currentWeek, newRows);
    showToast('Đã cập nhật nội dung tiết dạy!');
  };

  const handleInlineChange = (id: string, field: keyof LessonPlanRow, value: string) => {
    const newRows = displayRows.map((r) => {
      if (r.id === id) {
        return {
          ...r,
          [field]: value,
          isCustomized: true
        };
      }
      return r;
    });
    onSaveWeekRows(currentWeek, newRows);
  };

  const handleAddRow = () => {
    const newRow: LessonPlanRow = {
      id: `custom-row-${Date.now()}`,
      dayOfWeek: 2,
      dateStr: weekDates.startDate,
      session: 'Sáng',
      period: 1,
      className: '3A1',
      subject: 'Tin học',
      lessonName: 'Tiết học bổ sung',
      integrationNote: '',
      isCustomized: true
    };
    onSaveWeekRows(currentWeek, [...displayRows, newRow]);
    showToast('Đã thêm 1 dòng mới vào kế hoạch dạy học!');
  };

  const handleDeleteRow = (id: string) => {
    if (window.confirm('Bạn có chắc chắn muốn xóa dòng tiết học này không?')) {
      const newRows = displayRows.filter((r) => r.id !== id);
      onSaveWeekRows(currentWeek, newRows);
      showToast('Đã xóa dòng tiết học!');
    }
  };

  const handleResetToDefault = () => {
    if (window.confirm(`Khôi phục kế hoạch tuần ${currentWeek} về nguyên bản từ Thời khóa biểu và PPCT?`)) {
      onResetWeekRows(currentWeek);
      showToast(`Đã khôi phục kế hoạch tuần ${currentWeek}!`);
    }
  };

  const handleExportDocx = async () => {
    try {
      setIsExporting(true);
      await exportLessonPlanToDocx(
        config,
        currentWeek,
        weekDates.startDate,
        weekDates.endDate,
        displayRows
      );
      showToast(`Xuất file Word Tuần ${currentWeek} thành công!`);
    } catch (err) {
      console.error('Lỗi khi xuất Word:', err);
      alert('Có lỗi xảy ra khi tạo file Word. Vui lòng thử lại.');
    } finally {
      setIsExporting(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      {/* Toast notification */}
      {toastMessage && (
        <div className="fixed top-5 right-5 z-50 bg-teal-800 text-white text-xs font-black px-4 py-2.5 rounded-2xl shadow-xl border border-teal-600 flex items-center gap-2 animate-in slide-in-from-top duration-200">
          <Sparkles className="w-4 h-4 text-emerald-300" />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Control Bar: Chọn tuần, chuyển tuần, các nút hành động */}
      <div className="bg-white/95 backdrop-blur-md rounded-3xl p-4 sm:p-5 border-2 border-teal-200/80 shadow-lg shadow-teal-900/5 flex flex-col md:flex-row items-center justify-between gap-4">
        {/* Tuần Navigation */}
        <div className="flex items-center gap-3 w-full md:w-auto justify-between md:justify-start">
          <div className="flex items-center gap-1.5">
            <button
              type="button"
              disabled={currentWeek <= 1}
              onClick={() => setCurrentWeek((w) => Math.max(1, w - 1))}
              className="p-2 rounded-xl bg-teal-50 hover:bg-teal-100 text-teal-700 disabled:opacity-40 disabled:cursor-not-allowed transition-all cursor-pointer"
              title="Tuần trước"
            >
              <ChevronLeft className="w-5 h-5" />
            </button>

            <div className="flex items-center gap-2 px-3 py-1.5 rounded-2xl bg-teal-50/80 border border-teal-200">
              <Calendar className="w-4 h-4 text-teal-600" />
              <span className="text-xs font-bold text-slate-600">Tuần:</span>
              <select
                value={currentWeek}
                onChange={(e) => setCurrentWeek(Number(e.target.value))}
                className="bg-transparent font-black text-teal-800 text-sm focus:outline-none cursor-pointer"
              >
                {Array.from({ length: 35 }, (_, i) => i + 1).map((w) => (
                  <option key={w} value={w}>
                    Tuần {w}
                  </option>
                ))}
              </select>
            </div>

            <button
              type="button"
              disabled={currentWeek >= 35}
              onClick={() => setCurrentWeek((w) => Math.min(35, w + 1))}
              className="p-2 rounded-xl bg-teal-50 hover:bg-teal-100 text-teal-700 disabled:opacity-40 disabled:cursor-not-allowed transition-all cursor-pointer"
              title="Tuần kế tiếp"
            >
              <ChevronRight className="w-5 h-5" />
            </button>
          </div>

          <div className="text-left">
            <span className="text-xs font-extrabold text-slate-700 block">
              Từ {weekDates.startDate} đến {weekDates.endDate}
            </span>
            <span className="text-[11px] text-slate-500 font-medium">
              Tổng số: {displayRows.length} tiết dạy
            </span>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap items-center gap-2 w-full md:w-auto justify-end">
          <button
            type="button"
            onClick={handleAddRow}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold bg-teal-50 text-teal-700 hover:bg-teal-100 border border-teal-200 transition-all cursor-pointer"
            title="Thêm 1 dòng tiết học thủ công"
          >
            <Plus className="w-4 h-4" />
            <span>Thêm dòng</span>
          </button>

          {customizedWeeks[currentWeek] && (
            <button
              type="button"
              onClick={handleResetToDefault}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold bg-amber-50 text-amber-700 hover:bg-amber-100 border border-amber-200 transition-all cursor-pointer"
              title="Khôi phục dữ liệu gốc theo Thời khóa biểu và PPCT"
            >
              <RotateCcw className="w-4 h-4" />
              <span>Khôi phục gốc</span>
            </button>
          )}

          <button
            type="button"
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold bg-slate-100 text-slate-700 hover:bg-slate-200 transition-all cursor-pointer"
            title="In văn bản"
          >
            <Printer className="w-4 h-4" />
            <span>In</span>
          </button>

          <button
            type="button"
            disabled={isExporting}
            onClick={handleExportDocx}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-black bg-gradient-to-r from-teal-600 to-emerald-600 hover:from-teal-700 hover:to-emerald-700 text-white shadow-md shadow-teal-600/25 transition-all cursor-pointer disabled:opacity-50"
          >
            <Download className="w-4 h-4" />
            <span>{isExporting ? 'Đang xuất...' : 'Xuất Word (.docx)'}</span>
          </button>
        </div>
      </div>

      {/* Main Document Layout - Styled exactly like the attached PDF sample */}
      <div className="bg-white rounded-2xl p-6 sm:p-12 border border-slate-300 shadow-xl shadow-slate-200/50 print:shadow-none print:border-none print:p-0 max-w-5xl mx-auto font-serif text-slate-900">
        {/* Document Header (Trường & Tổ chuyên môn bên trái, Quốc hiệu bên phải) */}
        <div className="grid grid-cols-2 gap-4 text-center mb-6">
          <div className="flex flex-col items-center">
            <p className="text-xs sm:text-sm font-normal text-slate-900 uppercase tracking-tight">
              {config.schoolName || 'TRƯỜNG TIỂU HỌC THẠNH YÊN 1'}
            </p>
            <div className="relative inline-block mt-0.5">
              <p className="text-xs sm:text-sm font-bold text-slate-900 uppercase tracking-tight pb-0.5">
                {config.departmentName || 'TỔ CHUYÊN MÔN 4+5'}
              </p>
              <div className="w-full h-[1.5px] bg-slate-900 mx-auto" />
            </div>
          </div>
          <div className="flex flex-col items-center">
            <p className="text-xs sm:text-sm font-bold text-slate-900 uppercase tracking-tight">
              {config.republicTitleTop || 'CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM'}
            </p>
            <div className="relative inline-block mt-0.5">
              <p className="text-xs sm:text-sm font-bold text-slate-900 pb-0.5">
                {config.republicTitleSub || 'Độc lập – Tự do – Hạnh phúc'}
              </p>
              <div className="w-full h-[1.5px] bg-slate-900 mx-auto" />
            </div>
          </div>
        </div>

        {/* Title */}
        <div className="text-center my-6 space-y-1">
          <h2 className="text-lg sm:text-xl font-bold text-slate-900 uppercase tracking-tight">
            {config.documentTitle || 'KẾ HOẠCH DẠY HỌC'}
          </h2>
          <h3 className="text-sm sm:text-base font-bold text-slate-900 uppercase tracking-tight">
            {config.subjectTitle || 'MÔN: TIN HỌC - CÔNG NGHỆ'}
          </h3>
          <p className="text-xs sm:text-sm italic text-slate-800">
            Tuần {currentWeek} thực hiện từ ngày {weekDates.startDate} đến ngày {weekDates.endDate}
          </p>
        </div>

        {/* Table of Lessons matching attached PDF */}
        <div className="overflow-x-auto my-4">
          <table className="w-full text-xs border-collapse border border-black text-slate-900">
            <thead>
              <tr className="bg-white text-slate-900 text-center font-bold text-xs uppercase">
                <th className="py-2.5 px-2 border border-black w-24 align-middle">THỨ</th>
                <th className="py-2.5 px-2 border border-black w-18 align-middle">BUỔI</th>
                <th className="py-2.5 px-2 border border-black w-14 align-middle">TIẾT</th>
                <th className="py-2.5 px-2 border border-black w-18 align-middle">LỚP</th>
                <th className="py-2.5 px-2 border border-black w-28 align-middle">MÔN</th>
                <th className="py-2.5 px-3 border border-black min-w-[240px] align-middle">TÊN BÀI DẠY</th>
                <th className="py-2.5 px-2 border border-black min-w-[160px] align-middle text-center">
                  <div className="leading-tight">ĐIỀU CHỈNH/</div>
                  <div className="leading-tight">TÍCH HỢP</div>
                </th>
                <th className="py-2.5 px-1 border border-black w-14 print:hidden align-middle">TÁC VỤ</th>
              </tr>
            </thead>
            <tbody>
              {rowSpanData.length === 0 ? (
                // Nếu chưa có dữ liệu, hiển thị khung bảng chuẩn như mẫu đính kèm
                Array.from({ length: 6 }).map((_, i) => (
                  <tr key={`empty-${i}`} className="h-8">
                    {i === 0 && (
                      <td rowSpan={6} className="border border-black text-center align-middle font-bold text-slate-400">
                        (Chưa có tiết dạy)
                      </td>
                    )}
                    {i === 0 && (
                      <td rowSpan={3} className="border border-black text-center align-middle font-bold text-slate-400">
                        Sáng
                      </td>
                    )}
                    {i === 3 && (
                      <td rowSpan={3} className="border border-black text-center align-middle font-bold text-slate-400">
                        Chiều
                      </td>
                    )}
                    <td className="border border-black text-center text-slate-400">{(i % 3) + 1}</td>
                    <td className="border border-black"></td>
                    <td className="border border-black"></td>
                    <td className="border border-black"></td>
                    <td className="border border-black"></td>
                    <td className="border border-black print:hidden"></td>
                  </tr>
                ))
              ) : (
                rowSpanData.map(({ row, daySpan, sessionSpan }, idx) => (
                  <tr key={row.id || idx} className="hover:bg-amber-50/30 transition-colors group">
                    {/* THỨ (Gom ô cho toàn bộ các tiết trong ngày) */}
                    {daySpan > 0 && (
                      <td
                        rowSpan={daySpan}
                        className="py-2 px-2 text-center border border-black font-bold align-middle bg-white text-slate-900"
                      >
                        <div className="font-bold whitespace-nowrap">{getDayOfWeekName(row.dayOfWeek)}</div>
                        <div className="text-[10px] text-slate-500 font-normal">({row.dateStr})</div>
                      </td>
                    )}

                    {/* BUỔI (Gom ô cho toàn bộ các tiết trong buổi của ngày) */}
                    {sessionSpan > 0 && (
                      <td
                        rowSpan={sessionSpan}
                        className="py-2 px-2 text-center border border-black font-bold align-middle bg-white text-slate-900"
                      >
                        {row.session}
                      </td>
                    )}

                    {/* TIẾT */}
                    <td className="py-2 px-1 text-center border border-black font-bold align-middle">
                      {row.period}
                    </td>

                    {/* LỚP */}
                    <td className="py-2 px-2 text-center border border-black font-bold align-middle">
                      {row.className}
                    </td>

                    {/* MÔN */}
                    <td className="py-2 px-2 text-center border border-black align-middle">
                      {row.subject}
                    </td>

                    {/* TÊN BÀI DẠY */}
                    <td className="py-1.5 px-2 text-left border border-black align-middle font-medium">
                      <input
                        type="text"
                        value={row.lessonName}
                        onChange={(e) => handleInlineChange(row.id, 'lessonName', e.target.value)}
                        className="w-full bg-transparent hover:bg-slate-50 focus:bg-white px-1.5 py-1 rounded border border-transparent hover:border-slate-300 focus:border-teal-500 focus:outline-none transition-all text-xs"
                      />
                    </td>

                    {/* ĐIỀU CHỈNH/ TÍCH HỢP */}
                    <td className="py-1.5 px-2 text-left border border-black align-middle">
                      <input
                        type="text"
                        value={row.integrationNote || ''}
                        placeholder="..."
                        onChange={(e) => handleInlineChange(row.id, 'integrationNote', e.target.value)}
                        className="w-full bg-transparent hover:bg-slate-50 focus:bg-white px-1.5 py-1 rounded border border-transparent hover:border-slate-300 focus:border-teal-500 focus:outline-none transition-all text-xs"
                      />
                    </td>

                    {/* TÁC VỤ */}
                    <td className="py-1 px-1 text-center border border-black print:hidden align-middle">
                      <div className="flex items-center justify-center gap-1 opacity-60 group-hover:opacity-100 transition-opacity">
                        <button
                          type="button"
                          onClick={() => setEditingRow(row)}
                          className="p-1 rounded text-teal-700 hover:bg-teal-50 cursor-pointer"
                          title="Chỉnh sửa chi tiết"
                        >
                          <Edit2 className="w-3.5 h-3.5" />
                        </button>
                        <button
                          type="button"
                          onClick={() => handleDeleteRow(row.id)}
                          className="p-1 rounded text-rose-600 hover:bg-rose-50 cursor-pointer"
                          title="Xóa dòng"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Footer Signatures matching attached PDF:
            Date on right, then 3 columns: DUYỆT CỦA P.HIỆU TRƯỜNG | TỔ TRƯỞNG | GIÁO VIÊN */}
        <div className="mt-8 pt-4">
          <div className="flex justify-end pr-4 sm:pr-10 mb-3">
            <p className="text-xs sm:text-sm italic text-slate-800">
              {config.location || 'Vĩnh Hòa'}, ngày .... tháng .... năm ....
            </p>
          </div>

          <div className="grid grid-cols-3 gap-2 sm:gap-4 text-center">
            {/* Cột 1: DUYỆT CỦA P.HIỆU TRƯỜNG */}
            <div className="flex flex-col items-center">
              <p className="text-xs sm:text-sm font-bold text-slate-900 uppercase tracking-tight">
                {config.principalTitle || 'DUYỆT CỦA P.HIỆU TRƯỜNG'}
              </p>
              <div className="h-20 sm:h-24 flex items-center justify-center">
                {/* Khoảng trống ký tên & đóng dấu */}
              </div>
              <p className="text-xs sm:text-sm font-bold text-slate-900">
                {config.principalName || ''}
              </p>
            </div>

            {/* Cột 2: TỔ TRƯỞNG */}
            <div className="flex flex-col items-center">
              <p className="text-xs sm:text-sm font-bold text-slate-900 uppercase tracking-tight">
                {config.headTeacherTitle || 'TỔ TRƯỞNG'}
              </p>
              <div className="h-20 sm:h-24 flex items-center justify-center">
                {/* Khoảng trống ký tên */}
              </div>
              <p className="text-xs sm:text-sm font-bold text-slate-900">
                {config.headTeacherName || ''}
              </p>
            </div>

            {/* Cột 3: GIÁO VIÊN */}
            <div className="flex flex-col items-center">
              <p className="text-xs sm:text-sm font-bold text-slate-900 uppercase tracking-tight">
                {config.teacherTitle || 'GIÁO VIÊN'}
              </p>
              <div className="h-20 sm:h-24 flex items-center justify-center">
                {/* Khoảng trống ký tên */}
              </div>
              <p className="text-xs sm:text-sm font-bold text-slate-900">
                {config.teacherName || 'Nguyễn Tấn Luận'}
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Modal chỉnh sửa chi tiết */}
      <LessonDetailModal
        isOpen={Boolean(editingRow)}
        lesson={editingRow}
        onClose={() => setEditingRow(null)}
        onSave={handleUpdateRow}
      />
    </div>
  );
};
